description: "Аутентификация"
post:
    description: "Получение токена"
    is: !include ../../../../../../../../../zndoc/rest-api/src/is/post204.raml
    body:
        application/json:
            example: !include example/post-request-body.json
    responses:
        204:
            headers:
                Authorization:
                    type: string
                    description: Токен
                    example: 'jwt eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImM4NGQyYTU0LTgyY2ItNGY5Ny1hYjJhLWE5MmFmNjM2ZmY1OCJ9.eyJpc3MiOiJodHRwOlwvXC9hcGkueXVuZXdzLnByb2plY3RcL3YxXC9hdXRoIiwic3ViamVjdCI6eyJpZCI6MTQ2fSwiYXVkIjpbImh0dHA6XC9cL2FwaS55dW5ld3MucHJvamVjdCJdLCJleHAiOjE1NDU4MzAwNjV9.iGOF9CzAUH2ZEoZzw__JkdGrWO0kH9zTh-HzP9hxrfk'
get:
    securedBy: [bearerAuth]
    description: Получение информации текущего пользователя
    is: !include ../../../../../../../../../zndoc/rest-api/src/is/simple/one.raml
    responses:
        200:
            body:
                application/json:
                    example: !include example/one-reponse-body.json
