wsdl_definition:
    path: definition/{name}.wsdl
    controller: ZnSandbox\Sandbox\Wsdl\Symfony\Api\Controllers\HelloServiceController::definition
    requirements:
        name: '.+'

wsdl_run:
    path: handle/{name}
    controller: ZnSandbox\Sandbox\Wsdl\Symfony\Api\Controllers\HelloServiceController::handle
    requirements:
        name: '.+'

wsdl_test:
    path: test
    controller: ZnSandbox\Sandbox\Wsdl\Symfony\Api\Controllers\HelloServiceController::test
