<?php

use ZnSandbox\Sandbox\Casbin\Domain\Enums\Rbac\RbacItemEnum;
use ZnSandbox\Sandbox\Casbin\Rpc\Controllers\RoleController;

return [
   /* [
        'method_name' => 'rbacItem.all',
        'version' => '1',
        'is_verify_eds' => false,
        'is_verify_auth' => true,
        'permission_name' => 'oRbacItemAll',
        'handler_class' => 'ZnSandbox\Sandbox\Casbin\Rpc\Controllers\ItemController',
        'handler_method' => 'all',
        'status_id' => 100,
    ],*/

    [
        'method_name' => 'rbacAssignment.attach',
        'version' => '1',
        'is_verify_eds' => false,
        'is_verify_auth' => true,
        'permission_name' => \ZnSandbox\Sandbox\Casbin\Domain\Enums\Rbac\RbacAssignmentEnum::ATTACH,
        'handler_class' => \ZnSandbox\Sandbox\Casbin\Rpc\Controllers\AssignmentController::class,
        'handler_method' => 'attach',
        'status_id' => 100,
    ],
    [
        'method_name' => 'rbacAssignment.detach',
        'version' => '1',
        'is_verify_eds' => false,
        'is_verify_auth' => true,
        'permission_name' => \ZnSandbox\Sandbox\Casbin\Domain\Enums\Rbac\RbacAssignmentEnum::DETACH,
        'handler_class' => \ZnSandbox\Sandbox\Casbin\Rpc\Controllers\AssignmentController::class,
        'handler_method' => 'detach',
        'status_id' => 100,
    ],
    [
        'method_name' => 'rbacAssignment.allRoles',
        'version' => '1',
        'is_verify_eds' => false,
        'is_verify_auth' => true,
        'permission_name' => \ZnSandbox\Sandbox\Casbin\Domain\Enums\Rbac\RbacAssignmentEnum::DETACH,
        'handler_class' => \ZnSandbox\Sandbox\Casbin\Rpc\Controllers\AssignmentController::class,
        'handler_method' => 'allRoles',
        'status_id' => 100,
    ],


    [
        'method_name' => 'rbacRole.all',
        'version' => '1',
        'is_verify_eds' => false,
        'is_verify_auth' => true,
        'permission_name' => RbacItemEnum::ALL,
        'handler_class' => RoleController::class,
        'handler_method' => 'all',
        'status_id' => 100,
    ],
    [
        'method_name' => 'rbacRole.oneById',
        'version' => '1',
        'is_verify_eds' => false,
        'is_verify_auth' => true,
        'permission_name' => 'oRbacItemOne',
        'handler_class' => 'ZnSandbox\Sandbox\Casbin\Rpc\Controllers\RoleController',
        'handler_method' => 'oneById',
        'status_id' => 100,
    ],
    [
        'method_name' => 'rbacRole.create',
        'version' => '1',
        'is_verify_eds' => false,
        'is_verify_auth' => true,
        'permission_name' => 'oRbacItemCreate',
        'handler_class' => 'ZnSandbox\Sandbox\Casbin\Rpc\Controllers\RoleController',
        'handler_method' => 'add',
        'status_id' => 100,
    ],
    [
        'method_name' => 'rbacRole.update',
        'version' => '1',
        'is_verify_eds' => false,
        'is_verify_auth' => true,
        'permission_name' => 'oRbacItemUpdate',
        'handler_class' => 'ZnSandbox\Sandbox\Casbin\Rpc\Controllers\RoleController',
        'handler_method' => 'update',
        'status_id' => 100,
    ],
    [
        'method_name' => 'rbacRole.delete',
        'version' => '1',
        'is_verify_eds' => false,
        'is_verify_auth' => true,
        'permission_name' => 'oRbacItemDelete',
        'handler_class' => 'ZnSandbox\Sandbox\Casbin\Rpc\Controllers\RoleController',
        'handler_method' => 'delete',
        'status_id' => 100,
    ],

    // permission

    [
        'method_name' => 'rbacPermission.all',
        'version' => '1',
        'is_verify_eds' => false,
        'is_verify_auth' => true,
        'permission_name' => 'oRbacItemAll',
        'handler_class' => 'ZnSandbox\Sandbox\Casbin\Rpc\Controllers\PermissionController',
        'handler_method' => 'all',
        'status_id' => 100,
    ],
    [
        'method_name' => 'rbacPermission.oneById',
        'version' => '1',
        'is_verify_eds' => false,
        'is_verify_auth' => true,
        'permission_name' => 'oRbacItemOne',
        'handler_class' => 'ZnSandbox\Sandbox\Casbin\Rpc\Controllers\PermissionController',
        'handler_method' => 'oneById',
        'status_id' => 100,
    ],
    [
        'method_name' => 'rbacPermission.create',
        'version' => '1',
        'is_verify_eds' => false,
        'is_verify_auth' => true,
        'permission_name' => 'oRbacItemCreate',
        'handler_class' => 'ZnSandbox\Sandbox\Casbin\Rpc\Controllers\PermissionController',
        'handler_method' => 'add',
        'status_id' => 100,
    ],
    [
        'method_name' => 'rbacPermission.update',
        'version' => '1',
        'is_verify_eds' => false,
        'is_verify_auth' => true,
        'permission_name' => 'oRbacItemUpdate',
        'handler_class' => 'ZnSandbox\Sandbox\Casbin\Rpc\Controllers\PermissionController',
        'handler_method' => 'update',
        'status_id' => 100,
    ],
    [
        'method_name' => 'rbacPermission.delete',
        'version' => '1',
        'is_verify_eds' => false,
        'is_verify_auth' => true,
        'permission_name' => 'oRbacItemDelete',
        'handler_class' => 'ZnSandbox\Sandbox\Casbin\Rpc\Controllers\PermissionController',
        'handler_method' => 'delete',
        'status_id' => 100,
    ],
];