<?php

namespace ZnSandbox\Sandbox\RpcClient\Domain\Services;

use ZnCore\Base\Enums\StatusEnum;
use ZnCore\Domain\Libs\Query;
use ZnSandbox\Sandbox\RpcClient\Domain\Interfaces\Services\FavoriteServiceInterface;
use ZnCore\Domain\Interfaces\Libs\EntityManagerInterface;
use ZnSandbox\Sandbox\RpcClient\Domain\Interfaces\Repositories\FavoriteRepositoryInterface;
use ZnCore\Domain\Base\BaseCrudService;
use ZnSandbox\Sandbox\RpcClient\Domain\Entities\FavoriteEntity;

/**
 * @method
 * FavoriteRepositoryInterface getRepository()
 */
class FavoriteService extends BaseCrudService implements FavoriteServiceInterface
{

    public function __construct(EntityManagerInterface $em)
    {
        $this->setEntityManager($em);
    }

    public function getEntityClass() : string
    {
        return FavoriteEntity::class;
    }

    /*protected function forgeQuery(Query $query = null)
    {
        return parent::forgeQuery($query)
            ->where('status_id', StatusEnum::ENABLED);
    }*/

    public function allFavorite(Query $query = null)
    {
        $query = $this->forgeQuery($query);
        $query->where('status_id', StatusEnum::ENABLED);
        return parent::all($query); // TODO: Change the autogenerated stub
    }

    public function allHistory(Query $query = null)
    {
        $query = $this->forgeQuery($query);
        $query->where('status_id', StatusEnum::WAIT_APPROVING);
        return parent::all($query); // TODO: Change the autogenerated stub
    }
}
