type: x-custom
#description: Авторизация по токену
describedBy:
    headers:
        Authorization:
            description: Авторизация по токену
            type: string
            example: "c0bec554c5dda6a9cefc06dd6d65d3de"
    responses:
        401:
            description: "Аутентификация завершилась неудачно."
        403:
            description: "Аутентифицированному пользователю не разрешен доступ к указанной точке входа API"
