responses:
  404:
    description: "Запрошенный ресурс не существует."
    # body:
      # application/json:
        # example: |
          # {
            # "name": "Not Found",
            # "message": "Object not found: <id>",
            # "code": 0,
            # "status": 404
          # }
